apiVersion: cloudamqp.m.evaneos.com/v1alpha1
kind: IntegrationPrometheus
metadata:
  annotations:
    meta.upbound.io/example-id: cloudamqp/v1alpha1/integrationprometheus
  labels:
    testing.upbound.io/example-name: newrelic_v3
  name: newrelic-v3
  namespace: upbound-system
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: instance
    newrelicV3:
    - apiKeySecretRef:
        key: example-key
        name: example-secret
      tags: key=value,key2=value2
