apiVersion: cloudamqp.evaneos.com/v1alpha1
kind: Prometheus
metadata:
  annotations:
    meta.upbound.io/example-id: cloudamqp/v1alpha1/prometheus
  labels:
    testing.upbound.io/example-name: newrelic_v3
  name: newrelic-v3
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: instance
    newrelicV3:
    - apiKeySecretRef:
        key: example-key
        name: example-secret
        namespace: upbound-system
      tags: key=value,key2=value2
